name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 9.x
                  include-prerelease: true

            - name: Publish .NET Core Project
              run: dotnet publish muazzinapp.csproj -c Release -o release --nologo

            - name: copy index.html to 404.html
              run: cp release/wwwroot/index.html 

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            - name: Commit wwwroot to GitHub Pages
              uses: muhammadhafiz18/muazzinapp-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: release/wwwroot
